In [6]:
import numpy as np

X = np.array([[2,9],[1,6],[3,6]], dtype=float)
Y = np.array([[92],[86],[89]], dtype=float)
X = X/np.amax(X, axis=0)
actual_output = Y/100

print('normalised i/p\n',X,'\nactual output\n',actual_output)

normalised i/p
 [[0.66666667 1.        ]
 [0.33333333 0.66666667]
 [1.         0.66666667]] 
actual output
 [[0.92]
 [0.86]
 [0.89]]


In [7]:
def sigmoid(x):
  return 1/(1+np.exp(x))

def derivative_sigmoid(x):
  return x * (1-x)

In [8]:
epoch = 1000
learning_rate = 0.15
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

wh = np.random.uniform(low=-0.05, high=0.05, size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(low=-0.05, high=0.05, size=(1, hiddenlayer_neurons))

wo = np.random.uniform(low=-0.05, high=0.05, size=(hiddenlayer_neurons, outputlayer_neurons))
bo = np.random.uniform(low=-0.05, high=0.05, size=(1, outputlayer_neurons))

# print(wh, wo, bh, bo)

In [9]:
#training data
for i in range(epoch):
  #feed forward
  net_h = np.dot(X, wh) + bh
  sigma_h = sigmoid(net_h)

  net_o = np.dot(sigma_h, wo) + bo
  output = sigmoid(net_o)

  #back propagation
  #ouput layer error
  eo = actual_output - output
  outgrad = derivative_sigmoid(output)
  d_output = eo * outgrad

  #hidden layer error
  eh = d_output.dot(wo.T)
  hiddengrad = derivative_sigmoid(sigma_h)
  d_hidden = eh * hiddengrad

  #calc w = w + Δw
  wh += X.T.dot(d_hidden) * learning_rate
  wo += sigma_h.T.dot(d_output) * learning_rate

  sum_error = 0
  for j in range(len(actual_output)):
    sum_error += (actual_output - output)**2
  
  sum_error /= 2
  #print(f'Epoch {i} \nError {sum_error}')

In [10]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.66666667]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.50040357]
 [0.4405309 ]
 [0.49783607]]
