In [20]:
import numpy as np
X = np.array(([2,9], [1,5], [3,6]), dtype = float)
Y = np.array(([92], [86], [89]), dtype = float)
X = X/np.amax(X, axis=0)
actual_output = Y/100

print(f'input\n{X}')
print(f'output\n{Y}')


input
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
output
[[92.]
 [86.]
 [89.]]


In [21]:
#init
EPOCH = 1000
eta = 0.15
num_ip_neurons = 2
num_hidden_neurons = 3
num_op_neurons = 1

wh = np.random.uniform(low = -0.05, high = 0.05, size = (num_ip_neurons, num_hidden_neurons))
bh = np.random.uniform(low = -0.05, high = 0.05, size = (1, num_hidden_neurons))

wo = np.random.uniform(low = -0.05, high = 0.05, size = (num_hidden_neurons, num_op_neurons))
bo = np.random.uniform(low = -0.05, high = 0.05, size = (1, num_op_neurons))

In [22]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative_sigmoid(x):
    return x * (1-x)
    

In [23]:
for i in range(EPOCH):
    #feed forward n/w 
    net_h = np.dot(X, wh) + bh
    sigma_h = sigmoid(net_h)
    
    net_o = np.dot(sigma_h, wo) + bo
    output = sigmoid(net_o)
    
    #propagating backwards
    #error at o/p layer
    eo = actual_output - output
    out_grad = derivative_sigmoid(output)
    del_output = eo * out_grad
    
    #error at hidden layer
    eh = del_output.dot(wo.T)
    hidden_grad = derivative_sigmoid(sigma_h)
    del_hidden = eh * hidden_grad
    
    #calculating weights 
    wo += sigma_h.T.dot(del_output) * eta
    wh += X.T.dot(del_hidden) * eta
    
    sum_error = 0
    for j in range(len(actual_output)):
        sum_error += (actual_output[j] - output[j])**2
    
    sum_error = sum_error/2
    
    
    

In [24]:
print(f'The actual output is: \n{actual_output}\n')
print(f'The predicted output is: \n{output}\n')
print(f'The error is: \n{sum_error}\n')

The actual output is: 
[[0.92]
 [0.86]
 [0.89]]

The predicted output is: 
[[0.89567399]
 [0.87993844]
 [0.89436542]]

The error is: 
[0.00050418]

