In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
# print(iris.DESCR) #to print/check dataset
X = iris.data
y = iris.target
# print(X[:5])
# print(y)
labels = iris.target_names
# print(labels)
target_names = [labels[t] for t in y] #storing the labels names in a list (string)
# print(target_names)

In [2]:
#spliting our model into training & testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 23) #20% test

print('Training set (80%)', len(X_train))
print('Test set (20%)', len(X_test))

Training set (80%) 120
Test set (20%) 30


In [3]:
#train the model 
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(y_pred)

knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train, y_train)
y_pred5 = knn5.predict(X_test)
print(y_pred5)

knn80 = KNeighborsClassifier(n_neighbors=80)
knn80.fit(X_train, y_train)
y_pred80 = knn80.predict(X_test)
print(y_pred80)

[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 1 1 1 2 0 2 0 0 0 2 0 0 2 1 1]
[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 2 1 1 2 0 2 0 0 0 2 0 0 2 1 1]
[1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1]


In [4]:
actual = [labels[t] for t in y_test]
predicted_k1 = [labels[t] for t in y_pred]
predicted_k5 = [labels[t] for t in y_pred5]
print("Actual \t\t Predicted(k=1) \t\t Predictions")
for i in range(len(actual)):
    correct = 'No'
    if(actual[i] == predicted_k1[i]):
        correct = 'Yes'
    print(f'{actual[i]:10s} \t\t {predicted_k1[i]} \t\t {correct}')

print('When k=5\n')
print("Actual \t\t Predicted(k=5) \t\t Predictions")
for i in range(len(actual)):
    correct = 'No'
    if(actual[i] == predicted_k1[i]):
        correct = 'Yes'
    print(f'{actual[i]:10s} \t\t {predicted_k5[i]} \t\t {correct}')

Actual 		 Predicted(k=1) 		 Predictions
virginica  		 virginica 		 Yes
virginica  		 virginica 		 Yes
versicolor 		 versicolor 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
versicolor 		 versicolor 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
setosa     		 setosa 		 Yes
versicolor 		 versicolor 		 Yes
versicolor 		 versicolor 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
setosa     		 setosa 		 Yes
setosa     		 setosa 		 Yes
virginica  		 versicolor 		 No
versicolor 		 versicolor 		 Yes
versicolor 		 versicolor 		 Yes
virginica  		 virginica 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
setosa     		 setosa 		 Yes
setosa     		 setosa 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
setosa     		 setosa 		 Yes
setosa     		 setosa 		 Yes
virginica  		 virginica 		 Yes
versicolor 		 versicolor 		 Yes
versicolor 		 versicolor 		 Yes
When k=5

Actual 		 Predicted(k=5) 		 Predictions
virginic

In [5]:
#checking our accuracy 
from sklearn.metrics import classification_report, confusion_matrix
print('When k=1\n')
print('Confusion Matrix\n', confusion_matrix(y_test, y_pred))
print('Classification Report\n', classification_report(y_test, y_pred))


When k=1

Confusion Matrix
 [[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.89      1.00      0.94         8
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [6]:
print('When k=5\n')
print('Confusion Matrix\n', confusion_matrix(y_test, y_pred5))
print('Classification Report\n', classification_report(y_test, y_pred5))

When k=5

Confusion Matrix
 [[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [7]:
print('When k=80\n')
print('Confusion Matrix\n', confusion_matrix(y_test, y_pred80))
print('Classification Report\n', classification_report(y_test, y_pred80))

When k=80

Confusion Matrix
 [[ 8  4  0]
 [ 0  8  0]
 [ 0 10  0]]
Classification Report
               precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.36      1.00      0.53         8
           2       0.00      0.00      0.00        10

    accuracy                           0.53        30
   macro avg       0.45      0.56      0.44        30
weighted avg       0.50      0.53      0.46        30



C:\Users\Rishita\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rishita\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rishita\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
